# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d67b336f100229d60678c570f1c833f688e31150a02cb20e86a30e81b249cae06f27a68b3279fa0ce21610d7bc6822347ca7046b71c58316ad9dd081dbf704f

test:
  secret_key_base: 9025ac4671e9753098c342aba7c7802c27f55e757ddc7f87f3dab4a22d8e6d170a3b24bc89113024755c37704b64a21ae39755ff2679e3a7eb772c9cdedea23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
